### ISSUE TITLE
WebsocketClient: "IP does not match IP whitelist" when whitelist is specified

### ISSUE THREAD

**Issue by mbana** [coinbase/coinbase-pro-node#201]
**Works:**

1. `AuthenticatedClient` with a whitelisted IP.
2. `WebsocketClient` when I do _not_ specify an IP to whitelist, aka, `IP Whitelist (Optional)`

I don't want to have to resort to using 2.

**Doesn't work:**

When I specify an IP to whitelist and attempt to use the `WebsocketClient` as below

```typescript
this.client = new WebsocketClient(
  ['BTC-EUR'],
  'wss://ws-feed.gdax.com',
  {
    key,
    secret,
    passphrase,
  }
);
```

this error comes out:

```
StreamConnection:open
StreamConnection:message - data:  { type: 'error',
  message: 'Sorry, you could not be authenticated: Unauthorized',
  reason: 'IP does not match IP whitelist' }
```

Any clues? Is there a proxy somewhere that is causing the backend to see a different IP than the one that is whitelisted?

**Comment by rmm5t** [comment]
I haven't tried to reproduce your issue myself yet, but I think this one is going to require someone directly from the GDAX team to chime in. 

/cc @fb55 @mihar

**Comment by tcnevin** [comment]
I'm trying to figure this out too.  The only clue I could find is here. https://docs.gdax.com/#fix-api
In regards to fix-api  "GDAX does not support static IP addresses. If your firewall rules require a static IP address, you will need to create a TCP proxy server with a static IP address which is capable of resolving an IP address using DNS." 

so I tried changing my code like this:

const websocket = new gdax.WebsocketClient(['BTC-USD'],
                                           dns.resolve4('ws-feed.gdax.com', function(err,rec){return 'wss://' + rec[0];}),
                                           {
                                                key: 'myKey',
                                                secret: 'mySecret',
                                                passphrase: 'myPassPhrase',
                                            },
                                           {channels:['ticker']},
                                          );
//but I get these errors:
--------------------------------------------------------------------
url.js:106
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
    at Url.parse (url.js:106:11)
    at Object.urlParse [as parse] (url.js:100:13)
    at WebSocket.initAsClient (/node_modules/ws/lib/WebSocket.js:530:25)
    at new WebSocket (/node_modules/ws/lib/WebSocket.js:70:20)
    at WebsocketClient.connect (/node_modules/gdax/lib/clients/websocket.js:35:19)
    at new WebsocketClient (/node_modules/gdax/lib/clients/websocket.js:27:10)
    at Object.<anonymous> (index.js:23:19)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
------------------------------------------------------------------------------

//I think I'm on the right track because

var dns = require('dns');
dns.resolve4('ws-feed.gdax.com', function(err,rec){console.dir(typeof('wss://' + rec[0]))});

// returns: 'string'

and 
var dns = require('dns');
dns.resolve4('ws-feed.gdax.com', function(err,rec){console.dir('wss://' + rec[0])});

returns: 'wss://104.16.108.31'

I realize that my solution is wrong because I'm declaring a constant that has variable data, so it's probably best to change websocket.js(which I noticed defines websocketURI in the class constructor).
After changing my code back and changing: 
websocket.js websocketURI = dns.resolve4('ws-feed.gdax.com', 
                                          function(err,rec){console.dir(typeof('wss://' + rec[0]))});
I get the original error:
message: 'Sorry, you could not be authenticated: Unauthorized',
  reason: 'IP does not match IP whitelist' 

Sorry for the run-on comment.
Any ideas? Maybe a port number is neccasary?

**Comment by fb55** [comment]
This was overlooked in the initial IP whitelisting implementation and should have been fixed recently.

**Comment by kirsan31** [comment]
it's not fixed yet, still have:
> Sorry, you could not be authenticated: Unauthorized
Reason: IP does not match IP whitelist
on websocket from correct IP :((((

**Comment by igostavro** [comment]
+1 Having the same problem

**Comment by ballantyne** [comment]
I also have noticed this problem.

**Comment by tcnevin** [comment]
I've noticed gdax allows you to whitelist IP with port number. I haven't been able to reliably create a websocket and specify and exact port, and I just moved on from this, but I thought there may be a possiblilty that specifiying the whitelisted ip and port number may allow for it to work. Has anyone tried this?

**Comment by igostavro** [comment]
@tcnevin I've tried specifying an IP and not, no good. Has anyone gotten this to work?

**Comment by tcnevin** [comment]
@igostavro what I mean is, I noticed every time I run the program, the port number is different. I also noticed on gdax, that you can whitelist an IP specifying an exact port number. So, if gdax is checking for a default port number when you don't specify one; then there would be a possible mismatch because of that.

**Comment by igostavro** [comment]
@tcnevin hmm doesn't look like i specified a port number as that wouldn't make sense.

it looks like : Whitelisted IP: XX.XXX.XXX.XXX and is the correct public ip.

Any movement on this? @fb55

**Comment by kirsan31** [comment]
Yea, any news? Or we need to rewrite (that can be rewritten) to Fix API?

**Comment by tcnevin** [comment]
I'd like to reiterate: My thought is it might work if you include the port number. GDAX accepts and saves whitlisted ip in the following format - XXX.XXX.XXX.XXX:PORT

However I wasn't able to specify a port number when opening a websocket. The port number is different every time as I can observe by issuing the following command on linux: ss -tpan

Therefore, if GDAX is looking for a specific port number it is most likely going to be a mismatch.

**Comment by ballantyne** [comment]
Hi,

I put together a FIX api client.  I think that it could help you get the same functionality.
https://github.com/ballantyne/gdax-fix

Let me know if you have any issues.  Pull requests are welcome.

**Comment by ballantyne** [comment]
Nevermind, the fix api client comment was related to the fact that the user stream wasn't working, I thought that was what this whitelist problem was related to.  My bad.

**Comment by igostavro** [comment]
Any movement here?

**Comment by AlexisWilke** [comment]
I got the same error and landed here.

It seems that it works just fine from the other APIs so why not this one? Could it be that you are testing with the CloudFlare IP address instead of our IPs? (Personally I don't understand how CloudFlare could help with the dynamic API except maybe to avoid DoS and such? But anyway...)

If I create a key without a whitelisted IP address, then I get things to work and receive a ton of data as expected.

**Comment by tradadi** [comment]
Just following up. Using a read-only API key without an IP filter for the authenticated web socket user channel, in conjunction with a IP filtered key to do operations via REST works well.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
